RedisDriverTest: testRedisDriver.cpp ../../dao/* ../../common/* 
	g++ testRedisDriver.cpp ../../dao/* ../../common/* -o testRedisDriver -std=c++11 -lrocketmq -llog4cpp -lpthread -lhiredis

clean : testRedisDriver
	rm -rf testRedisDriver